name: flutter_step_counter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  permission_handler: ^11.3.1
  
  intl:  ^0.20.2

  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.3
  isar_flutter_libs: ^3.1.0+1

  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

  cached_network_image: ^3.4.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

  pigeon: ^17.1.3

flutter:

  uses-material-design: true
